export interface City {
  name: string;
  lat: string;
  lon: string;
  href: string;
  imageSrc: string;
  altText: string;
  costOfLiving: string;
}

export const cityEmojiMap: { [key: string]: string } = {
  Chicago: "💨",
  Phoenix: "☀️",
  "San Antonio": "🤠",
  Honolulu: "🏝️",
};

export const cities: City[] = [
  {
    name: "Chicago",
    lat: "41.88",
    lon: "-87.62",
    href: "https://jobs.nm.org/employment/chicago-illinois-united-states-nursing-jobs/27763/68550/6252001-4896861-4888671-4887398/4",
    imageSrc: "/chicago.png",
    altText: "Chicago Skyline",
    costOfLiving: "$2,425/month",
  },
  {
    name: "Phoenix",
    lat: "33.44",
    lon: "-112.07",
    href: "https://jooble.org/jobs-rn/Phoenix%2C-AZ",
    imageSrc: "/phoenix.png",
    altText: "Phoenix Skyline",
    costOfLiving: "$2,445/month",
  },
  {
    name: "San Antonio",
    lat: "29.42",
    lon: "-98.49",
    href: "https://www.monster.com/jobs/q-nursing-jobs-l-san-antonio-tx",
    imageSrc: "/san_antonio.png",
    altText: "San Antonio Skyline",
    costOfLiving: "$2,051/month",
  },
  {
    name: "Honolulu",
    lat: "21.31",
    lon: "-157.85",
    href: "https://hawaiipacifichealth.jobs/nursing/new-jobs/",
    imageSrc: "/honolulu.png",
    altText: "Honolulu Skyline",
    costOfLiving: "$2,804/month",
  },
];

export const states = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const stateAbbreviations = {
  Alabama: "AL",
  Alaska: "AK",
  Arizona: "AZ",
  Arkansas: "AR",
  California: "CA",
  Colorado: "CO",
  Connecticut: "CT",
  Delaware: "DE",
  Florida: "FL",
  Georgia: "GA",
  Hawaii: "HI",
  Idaho: "ID",
  Illinois: "IL",
  Indiana: "IN",
  Iowa: "IA",
  Kansas: "KS",
  Kentucky: "KY",
  Louisiana: "LA",
  Maine: "ME",
  Maryland: "MD",
  Massachusetts: "MA",
  Michigan: "MI",
  Minnesota: "MN",
  Mississippi: "MI",
  Missouri: "MO",
  Montana: "MT",
  Nebraska: "NE",
  Nevada: "NV",
  "New Hampshire": "NH",
  "New Jersey": "NJ",
  "New Mexico": "NM",
  "New York": "NY",
  "North Carolina": "NC",
  "North Dakota": "ND",
  Ohio: "OH",
  Oklahoma: "OK",
  Oregon: "OR",
  Pennsylvania: "PA",
  "Rhode Island": "RI",
  "South Carolina": "SC",
  "South Dakota": "SD",
  Tennessee: "TN",
  Texas: "TX",
  Utah: "UT",
  Vermont: "VT",
  Virginia: "VA",
  Washington: "WA",
  "West Virginia": "WV",
  Wisconsin: "WI",
  Wyoming: "WY",
};
